name: Node.js Package
on:
  push:
    branches:
      - master

jobs:
  publish-grp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@nikulsprajapati"
      - run: npm install
      - run: npm publish
    env:
      NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
